# Security
security.private_key_file                     = private_keys.csv
security.public_key_file                      = public_keys.csv
security.supported_integrity_algorithms       = NONE,HMAC_SHA2_256,HMAC_SHA2_512,HMAC_BLAKE3
security.supported_confidentiality_algorithms = NONE,AES128,AES256,CHACHA20
security.supported_dhke_key_types             = X25519,SECP256R1,CURVE448

# Transports
transport.size          = 4
# Transport 0 - UC0 GLOBAL TRANSPORT
transport-0.name        = UC0
transport-0.type        = UNICAST
transport-0.bind        = 0.0.0.0:25000
transport-0.mtu         = 1500
# Transport 1 - UC1 GLOBAL TRANSPORT
transport-1.name        = UC1
transport-1.type        = UNICAST
transport-1.bind        = 0.0.0.0:25001
transport-1.mtu         = 1500
# Transport 2 - MC0 LOCAL TRANSPORT
transport-2.name        = MC0
transport-2.type        = INTERNAL_MULTICAST
transport-2.group       = 224.0.0.1
transport-2.port        = 12345
transport-2.interface   = 0.0.0.0
transport-2.mtu         = 1500
# Transport 3 - MC1 LOCAL BROADCAST
transport-3.name        = MC0
transport-3.type        = EXTERNAL_MULTICAST
transport-3.send        = 127.0.0.1:5000
transport-3.recv        = 127.0.0.1:5001
transport-3.mtu         = 1500

# Node
node.network.beacon_interval_ms             = 500
node.network.check_peer_activity_interval_s = 15
node.network.peer_timeout_s                 = 15
node.network.peer_security_ctx_timeout_s    = 120
node.network.peer_transaction_timeout_ms    = 500
node.network.network_key_seeder             = false
node.identity.size                          = 2
node.identity-0.node_id                     = 0:0:0:1
node.identity-0.ds_send                     = 127.0.0.1:5100
node.identity-0.ds_recv                     = 127.0.0.1:5101
node.identity-1.node_id                     = 0:0:0:2
node.identity-1.ds_send                     = 127.0.0.1:5200
node.identity-1.ds_recv                     = 127.0.0.1:5201
node.static_peer.size                       = 2
node.static_peer-0                          = therooftoppri.nz:12345
node.static_peer-1                          = fi1.therooftoppri.nz:12345