# transports
import cfg_transports.ini
# security
import cfg_security.ini
# node
node.identitiy.size     = 1
node.identity-0.node_id = FF:FF:10:04
# node static peers
node.peer.size        = 2
node.peer-0.transport = UDP4_UNICAST
node.peer-0.address   = therooftoppri.nz:12345
node.peer-1.transport = UDP4_UNICAST
node.peer-1.address   = fi1.therooftoppri.nz:12345