# transports
import cfg_transports.ini
# security
import cfg_security.ini
# node
node.id.size               = 1
node.id-0.node_id          = FF:FF:10:04
node.id-0.peer.size        = 1
node.id-0.peer-0.transport = UDP4_UNICAST
node.id-0.peer-0.address   = therooftoppri.nz:12345