# Transport
transport.size              = 1
transport-0.type            = UDP4_UNICAST
transport-0.capabilities    = HUB
transport-0.bind_address    = 0.0.0.0:12345
transport-0.peer_cache_file = peers.csv
transport-0.peer.size       = 1
transport-0.peer-0.address  = therooftoppri.nz:12345