# Confidentiality Suite
security.confidentiality_suite.size           = 4
security.confidentiality_suite-0.algorithm    = NONE
security.confidentiality_suite-1.algorithm    = AES128
security.confidentiality_suite-2.algorithm    = AES256
security.confidentiality_suite-3.algorithm    = CHACHA20
# Integrity Suite
security.integrity_suite.size                 = 4
security.integrity_suite-0.algorithm          = NONE
security.integrity_suite-1.algorithm          = HMAC_SHA2_512
security.integrity_suite-2.algorithm          = HMAC_SHA2_256
security.integrity_suite-3.algorithm          = HMAC_BLAKE3
# Key Files
security.private_key_file                     = private_keys.csv
security.public_key_file                      = public_keys.csv