# Confidentiality Suite
security.confidentiality_suite.size           = 4
security.confidentiality_suite-0.algorithm    = 0,NONE
security.confidentiality_suite-1.algorithm    = 1,AES128
security.confidentiality_suite-2.algorithm    = 2,AES256
security.confidentiality_suite-3.algorithm    = 3,CHACHA20
# Integrity Suite
security.integrity_suite.size                 = 4
security.integrity_suite-0.algorithm          = 0,NONE
security.integrity_suite-1.algorithm          = 1,HMAC_SHA2_512
security.integrity_suite-2.algorithm          = 2,HMAC_SHA2_256
security.integrity_suite-3.algorithm          = 3,HMAC_BLAKE3
# Key Files
security.private_key_file                     = private_keys.csv
security.public_key_file                      = public_keys.csv